### PR TITLE
alternate method for extracting the database

### PR DESCRIPTION
**Pull request by dustinrue**
### Description of the Change

When trying to use wpsnapshots on CentOS 7 the database extraction will fail because it ships with an older version of gzip that doesn't understand the `-k` option. This PR modifies the extraction process to avoid the issue while still keeping the original file.

### Benefits

This will allow wpsnapshots to work across more operating systems.

### Possible Drawbacks

I don't know if this will increase memory usage of the process.

### Verification Process

I tested this on my mac and tested the same command on CentOS Linux. It worked on both

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

No issue was opened for this

### Changelog Entry

More cross platform friendly database extraction method

### CODE REVIEW

**Comment by tlovett1** [comment]
Hey @dustinrue what OS's have you tested in this in?

**Comment by dustinrue** [comment]
macOS and CentOS. I did not try WSL but I could. Everything used are pretty standard Unix/Linux Utica though

**Comment by tlovett1** [comment]
Can anyone else give this a test?

**Comment by dinhtungdu** [comment]
@tlovett1 Tested on `CentOS Linux release 7.6.1810 (Core)` and this PR fixes the `gzip: invalid option -- 'k'` issue.

**Comment by jeffpaul** [comment]
@tlovett1 any updates on your review of this PR?

**Comment by jasondewitt** [comment]
This error is currently blocking me on a project, can we look at this one again? If it works on Mac and Centos we should be good, these are all standard lib tools.

**Pull request merged**
