### PR TITLE
Scrubs email addresses as well as passwords

### LINKED ISSUE #46: Feature Request: Add flag to scrub emails
Add a way to scrub emails on upload and/or download of database, just as we scrub passwords.

### PR DESCRIPTION
**Pull request by ChaosExAnima**
Resolves #46.

Note I have not tested this yet.

### CODE REVIEW

**Comment by ChaosExAnima** [comment]
Okay, performed tests:
1. Created new WP installation and generated 100 users.
2. Created a snapshot using `wpsnapshots create`.
3. Pulled in snapshot.

Results were that users had scrubbed emails (`user0@example.com`) instead of old emails. Passwords were changed as expected.

**Comment by tlovett1** [comment]
@ChaosExAnima can you rebase against master please?

**Comment by ChaosExAnima** [comment]
@tlovett1 - Done!

**Comment by tlovett1** [comment]
Awesome. Nice work.

**Pull request merged**
