### PR TITLE
Adds a progress bar

### LINKED ISSUE #27: Provide progress for S3 operations
I'd like to request the feature that a progress bar be added for S3 uploads/downloads. This looks to be feasible via the S3 API:
https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#progress

### PR DESCRIPTION
**Pull request by ChaosExAnima**
Fixes #27. Adds a progress bar to track S3 uploads and downloads.

@tlovett1 - What's the best way to test this? The dev environment here isn't clear to me.

### CODE REVIEW

**Comment by tlovett1** [comment]
Hey @ChaosExAnima, this is awesome! There isn't any dev environment. I'll test.

**Comment by ChaosExAnima** [comment]
@tlovett1 - Okay! I may spend some time next week adding a dev environment via Docker. If there's a test AWS bucket/db I can use that'd be appreciated :)

**Comment by ChaosExAnima** [comment]
@tlovett1 - Any word here? I'd love to get this up on Docker Hub as a beta for testing in projects.

**Comment by tlovett1** [comment]
@ChaosExAnima I feel like if we are adding one progress bar, we should add them everywhere anything is time consuming:
- Downloading a snapshot
- Exporting a database
- Importing a database
- Running search/replace on a database
- Compressing files

What are your thoughts? I'll ping you separately about the Docker thing.

**Comment by tlovett1** [comment]
Yea agreed we probably want to abstract out the progress bar code a bit. Want to update the PR with adding the progress bar to the entire list?

**Comment by ChaosExAnima** [comment]
Hey @tlovett1! I've implemented the progress bar across most operations as a generic class. If you can review when you get a sec, I would appreciate it!

**Comment by jeffpaul** [comment]
@tlovett1 any updates from your review on this one?

**Comment by jeffpaul** [comment]
@tlovett1 any updates on your review of this PR?

**Comment by ChaosExAnima** [comment]
Hey @jeffpaul! I'm no longer using this tool nor have any access to this repo, so I am not in a position to respond to issues.

**Pull request closed without merging**
